apiVersion: v2
name: keycloak
description: A Helm chart to deploy keycloak as OIDC provider in openmfp

type: application
version: 0.64.3
appVersion: "1.16.0"

dependencies:
  - name: keycloak
    alias: keycloak
    version: 24.7.1
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: common
    version: 0.5.2
    repository: oci://ghcr.io/openmfp/helm-charts
