apiVersion: v2
description: Helm Chart for the openmfp Portal
name: portal
version: 0.73.181
appVersion: "v0.377.151"
dependencies:
  - name: common
    repository: oci://ghcr.io/openmfp/helm-charts
    version: 0.5.2
