apiVersion: v2
version: 0.20.2
appVersion: v0.76.1
name: kubernetes-graphql-gateway
description: Basic helm chart that contains listener and gateway
dependencies:
  - name: common
    version: 0.5.2
    repository: oci://ghcr.io/openmfp/helm-charts
