apiVersion: v2
appVersion: "v0.158.7"
description: Helm Chart for the openmfp Portal
name: example-content
version: 0.114.32
dependencies:
  - name: common
    version: 0.5.2
    repository: oci://ghcr.io/openmfp/helm-charts
